name: Build Android Release

on:
  workflow_dispatch:
  push:
    branches:
      - feature/github-actions-build-and-release-android

jobs:
  build:
    name: Build Android Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Decode and save keystore
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 -d > android/keystore.jks

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build release APK
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: ./gradlew assembleRelease

      #- name: Upload APK as artifact
      #  uses: actions/upload-artifact@v3
      #  with:
      #  name: release-apk
      #  path: android/build/outputs/apk/release/android-release.apk

      - name: Get versionName from build.gradle
        id: get_version
        run: |
          VERSION_NAME=$(grep 'versionName' android/build.gradle | awk -F\" '{print $2}')
          echo "VERSION_NAME=${VERSION_NAME}" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION_NAME }}
          release_name: Release v${{ env.VERSION_NAME }}
          draft: true
          prerelease: false

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: android/build/outputs/apk/release/android-release.apk
          asset_name: BirdHunt_v${{ env.VERSION_NAME }}.apk
          asset_content_type: application/vnd.android.package-archive
